import { IsEnum, IsNotEmpty, IsString } from 'class-validator';

export class CreateAppraisalCycleDto {
  @IsString()
  @IsNotEmpty()
  name: string;

  @IsString()
  startDate: string;

  @IsString()
  endDate: string;

  @IsEnum(['upcoming', 'active', 'closed'], {
    message: 'Status must be upcoming, active, or closed',
  })
  status: 'upcoming' | 'active' | 'closed';

  isAutoGenerated?: boolean;
}
