import { IsString, IsDateString, IsOptional, IsBoolean } from 'class-validator';

export class CreateCycleDto {
  @IsString()
  name: string;

  @IsOptional()
  @IsString()
  description?: string;

  @IsDateString()
  startDate: string;

  @IsDateString()
  endDate: string;

  @IsOptional()
  @IsBoolean()
  isAutoGenerated?: boolean; // 'true' or 'false', default is 'false
}
