import {
  pgTable,
  uuid,
  text,
  date,
  timestamp,
  boolean,
  index,
} from 'drizzle-orm/pg-core';
import { companies } from 'src/drizzle/schema';

export const performanceCycles = pgTable(
  'performance_cycles',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    companyId: uuid('company_id')
      .notNull()
      .references(() => companies.id, { onDelete: 'cascade' }),
    name: text('name').notNull(), // e.g., 'Q4 2025 Review'
    description: text('description'), // Optional description
    startDate: date('start_date').notNull(),
    endDate: date('end_date').notNull(),
    status: text('status').default('draft'), // draft | active | closed
    createdAt: timestamp('created_at').defaultNow(),
    isAutoGenerated: boolean('is_auto_generated').default(false), // true or false
  },
  (table) => [index('company_name_idx').on(table.companyId, table.name)],
);
