import {
  pgTable,
  uuid,
  text,
  timestamp,
  varchar,
  boolean,
} from 'drizzle-orm/pg-core';
import { companies } from 'src/drizzle/schema';

export const performanceAppraisalCycles = pgTable(
  'performance_appraisal_cycles',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    companyId: uuid('company_id').references(() => companies.id, {
      onDelete: 'cascade',
    }),
    name: text('name').notNull(), // e.g. "Mid-Year 2025"
    startDate: varchar('start_date').notNull(),
    endDate: varchar('end_date').notNull(),
    status: text('status', {
      enum: ['upcoming', 'active', 'closed'],
    }).notNull(),
    isAutoGenerated: boolean('is_auto_generated').default(false),
    createdAt: timestamp('created_at').defaultNow(),
  },
);
